### ISSUE TITLE
Folder structure is not displayed in .zip archvies

### ISSUE THREAD

**Issue by tdolsen** [atom/archive-view#16]
OS: Windows 8.1
Atom: 0.175.0
archive-view: 0.44.0

When opening .tar, .tar.gz (and assuming .tgz and the rest of the bunch) I get a nice folder structure, and can easily follow the contents of the archive. (Notice 2 files and 1 folder.)

![tar gz](https://cloud.githubusercontent.com/assets/180510/5900855/99c876ec-a56d-11e4-91dd-ea74b6fbcc01.png)

However, when looking at .zip archives folders are interpreted as files, and there is just a flat structure - i.e. no folders. (Notice 3 files and 0 folders.)

![zip](https://cloud.githubusercontent.com/assets/180510/5900880/d4c611b4-a56d-11e4-95b6-3783fd0934f0.png)

The first time (does not happen subsequent times) opening a zip file the console spits out an error message too:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
(view error full stack at [gist tdolsen/1e7a5dc2bf1fb26026d6](https://gist.github.com/tdolsen/1e7a5dc2bf1fb26026d6))

The two archives are obviously based on the same folder with the same contents.

This isn't a big issue with small files like this, but looking through larger archives (which often are shipped as .zip) it becomes impossible to figure out which file is which, and where they reside in the directory structure.

:+1:

**Comment by kevinsawicki** [comment]
Could you share the file that isn't showing the structure correctly?

Here is the sample zip file I use for testing and it appears to show the structure:

![screen shot 2015-02-10 at 11 53 06 am](https://cloud.githubusercontent.com/assets/671378/6135196/817e084a-b11b-11e4-85ba-71b812f457bc.png)

This raw file is here: https://github.com/atom/node-ls-archive/blob/1b9428475138e41e6fbf27e7c48775dff998ba8a/spec/fixtures/nested.zip

**Comment by tdolsen** [comment]
Can't share the zip, but the same problem occurs with your test zip.

![nested-zip](https://cloud.githubusercontent.com/assets/180510/6138584/baadf30c-b182-11e4-9309-688d861ff05e.png)

**Comment by kevinsawicki** [comment]
> Can't share the zip, but the same problem occurs with your test zip.

Thanks for checking this, must be a platform specific issue then.

**Comment by tdolsen** [comment]
I guess so. Any information I can provide to help figure out the issue?

**Comment by Aarilight** [comment]
It's doing this for me as well. Anything I can do?

**Comment by Aarilight** [comment]
Yes, that's the problem, I modifed the object in the devtools inspector and it works. You need a function that replaces `\` with `/`
