### ISSUE TITLE
general question on View creation

### ISSUE THREAD

**Issue by djahma** [atom/archive-view#27]
sorry for asking this here, but I can't find an answer by myself. I'd like to create a view that ends up in atom tabs like your module does, but I can't seem to understand how to do that:-/ I'm a total noob, completely lost.

How is the view created? archive-editor.coffee is specified under "main" in package.json, but there's no "activationCommands". So how does the "ArchiveEditor" class gets instantiated, and the "activate" function called? Also, after "activate" is called, where is the "ArchiveEditorView" class being instantiated? I'm not seeing anything calling the "getViewClass" function.

thanks

**Comment by thomasjo** [comment]
Please open a topic on [Discuss](http://discuss.atom.io) or [Slack](http://atomio.slack.com). Although I can briefly mention that this package in particular leverages [`Workspace::addOpener`](https://atom.io/docs/api/v1.0.2/Workspace#instance-addOpener), as is evident in [archive-editor.coffee#L21-L26](https://github.com/atom/archive-view/blob/v0.58.0/lib/archive-editor.coffee#L21-L26).
