### ISSUE TITLE
Save to archive file

### ISSUE THREAD

**Issue by bcholfin** [atom/archive-view#29]
Not sure if this is the right place to ask for this--

I can open a file in an epub with the archive viewer in Atom and then edit it, that's fine. What I would like to do is save the file back to the epub directly, rather than having to save the file to disk and then manually reinsert it into the archive. (Unless there is a way to do this, and I am missing it.)

**Comment by damieng** [comment]
Updating and modifying archives is out of scope for 'archive-view' and would best be served by an additional package or 3rd party tool.
