### ISSUE TITLE
Add support for Microsoft Office XML files.

### ISSUE THREAD

**Issue by connerk** [atom/archive-view#33]
Any modern Microsoft Office file ([xls,doc,ppt][x,m,a] etc.) is a zipped file.
It would be great to be able to to view (and modify) the contents of these files.

or, adding the ability to modify the tile types list would support many of the feature requests I'm seeing at this time

Thanks for everything!

**Comment by lee-dohm** [comment]
We don't really have room for this on our roadmap. We do think that adding support for arbitrary archive file types is a good thing though! For this, we've opened #34 to see if someone in the community can add an API to allow for extending archive-view to make it easy for package authors to add this kind of thing. You may want to subscribe to #34 for updates.

While not exactly what you want, I hope this helps!
