### ISSUE TITLE
NaN folders count

### ISSUE THREAD

**Issue by smutnyleszek** [atom/archive-view#51]
### Description

I opened preview of a zip file. I can see the contents, but the info on top is a lie and a wtf ;-)

![screen shot 2017-06-08 at 14 13 41](https://user-images.githubusercontent.com/2521888/26928187-6bba10c6-4c55-11e7-852f-7e2b5b7c84e0.png)

### Steps to Reproduce

1. Open preview tab of `.zip` file

**Expected behavior:** It should be something like "3.65 MB with 99 files and 15 folders"

**Actual behavior:** It shows "3.65 MB with 0 files and NaN folders"

**Reproduces how often:** 100%

### Versions

```
OS: MacOS Sierra 10.12.5
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

**Comment by thomasjo** [comment]
Thanks for reporting this!

This has already been fixed in #50. It is currently scheduled for release when Atom 1.19 reaches Stable.
