### ISSUE TITLE
Object.provide is deprecated.

### ISSUE THREAD

**Issue by jeybin** [atom/archive-view#70]
The environment package is deprecated. Use process.env directly instead. https://github.com/atom/atom/pull/12562
```
Object.provide (C:\Users\ibh7\.atom\packages\environment\lib\main.js:19:23)
Package.activateServices (<embedded>:11:3020781)
Package.activateNow (<embedded>:11:3017902)
measure (<embedded>:11:3017226)
Package.measure (<embedded>:11:3014857)
activationPromise.activationPromise.Promise (<embedded>:11:3017086)
```

**Comment by jeybin** [comment]
Tried to update but it is showing as updated

![capture](https://user-images.githubusercontent.com/32933024/53692376-8c739900-3d43-11e9-8d59-4ba3b19ed825.PNG)

**Comment by 50Wliu** [comment]
The message is asking you to uninstall the `environment` package. If you still have questions, please post on [Discuss](https://discuss.atom.io), the official Atom and Electron message board.
